ALTER TABLE user
    ADD COLUMN createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
    ADD COLUMN updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE account
    ADD COLUMN updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
