CREATE TABLE user (
      id SERIAL PRIMARY KEY,
      username name VARCHAR(100)NOT NULL,
      password password VARCHAR(255) NOT NULL;
      Email VARCHAR(50) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);